#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include <stm32f4xx_hal.h>
#include <string.h>

#define GREEN_LED_PIN GPIO_PIN_12
#define ORANGE_LED_PIN GPIO_PIN_13
#define RED_LED_PIN GPIO_PIN_14
#define BLUE_LED_PIN GPIO_PIN_15

#define LED_GPIO_PORT GPIOD
#define LED_GPIO_CLK_ENABLE() __HAL_RCC_GPIOD_CLK_ENABLE()
#define BUTTON_GPIO_CLK_ENABLE() __HAL_RCC_GPIOA_CLK_ENABLE()

#define BUTTON_PIN GPIO_PIN_0
#define BUTTON_GPIO_PORT GPIOA
#define BUTTON_IRQn EXTI0_IRQn

#define DBG_UART USART2
#define DBG_UART_CLK_ENABLE() __HAL_RCC_USART2_CLK_ENABLE()
#define DBG_UART_RX_GPIO_CLK_ENABLE() __HAL_RCC_GPIOA_CLK_ENABLE()
#define DBG_UART_TX_GPIO_CLK_ENABLE() __HAL_RCC_GPIOA_CLK_ENABLE()
#define DBG_UART_TX_PIN GPIO_PIN_2
#define DBG_UART_TX_GPIO_PORT GPIOA
#define DBG_UART_RX_PIN GPIO_PIN_3
#define DBG_UART_RX_GPIO_PORT GPIOA

#ifdef __cplusplus
} // extern "C"
#endif
